using System;
using System.Collections.Generic;
using System.Linq.Expressions;


public class PromptGenerator
{

    private Random _random = new Random();



    //These prompts were taken from another database. They are not orginal work. I didn't think it mattered, I wanted to have a lot of choices. 

    public List<string> _prompts = new List<string>
        {
            "Who was the most interesting person I interacted with today?",
            "What was the best part of my day?",
            "How did I see the hand of the Lord in my life today?",
            "What was the strongest emotion I felt today?",
            "If I had one thing I could do over today, what would it be?",
            "How do you define happiness, and has that definition changed over time?",
            "What was the last goal you accomplished, and how did you celebrate?",
            "Describe a simple pleasure in life that never fails to cheer you up.",
            "What’s your favorite way to spend a rainy afternoon?",
            "How do you stay motivated on tasks that feel difficult or tedious?",
            "Write about a time you had an unexpected conversation that shaped your day.",
            "What’s something new you discovered about your own personality recently?",
            "If you could master any instrument instantly, which would it be and why?",
            "Recall a time when you had to adapt your plans on short notice. How did you handle it?",
            "Describe a childhood place that holds special memories for you.",
            "Who is a person you admire, and what qualities do you appreciate most in them?",
            "What was the last new skill you tried to learn? How did it go?",
            "How do you typically react to criticism, and how would you like to react instead?",
            "Write about a time when you felt truly understood by someone.",
            "Describe your perfect lazy day from start to finish.",
            "Do you believe people can truly change? Why or why not?",
            "Write about a time you stood up for something you believed in.",
            "What does balance look like in your life right now?",
            "What’s one routine you’d like to implement to improve your daily life?",
            "How do you express gratitude toward others?",
            "Describe a memory involving food that makes you smile.",
            "What’s a skill you learned as a child that you still use frequently?",
            "How do you manage expectations—both those of others and your own?",
            "What do you do when you feel creatively stuck?",
            "Recall a time you felt proud of someone else’s accomplishments.",
            "What’s your favorite way to show love or appreciation to friends or family?",
            "How do you deal with uncertainty about the future?",
            "Write about the best gift you’ve ever received (tangible or intangible).",
            "Which family tradition has been most meaningful to you?",
            "What was the last big risk you took? What did you learn from it?",
            "If your life were a book, what genre would it be and why?",
            "Describe a situation where you had to make a quick decision. How did it turn out?",
            "What’s one moment you wish you could relive, just to feel it again?",
            "If you had to spend a week in complete solitude, how would you handle it?",
            "Write about a teacher or mentor who had a profound impact on you.",
            "How do you define home?",
            "What’s one way you can be kinder to yourself today?",
            "Recall a time you made a positive difference for someone else.",
            "Who do you feel most comfortable being yourself around, and why?",
            "What’s your relationship with change? Do you embrace it or resist it?",
            "Describe a time you had to apologize. How did it feel?",
            "What’s your approach to making big decisions in life?",
            "Write about an act of courage you witnessed firsthand.",
            "Is there a quote or saying that resonates deeply with you? Why?",
            "Describe your happiest childhood memory.",
            "How do you handle being wrong about something?",
            "What’s your favorite form of creative expression (writing, art, music, etc.)?",
            "Write about the last time you felt a spark of inspiration.",
            "What’s the best piece of advice you’ve ever given someone else?",
            "Reflect on a time you successfully navigated a cultural or language barrier.",
            "Describe the qualities you look for in a true friend.",
            "What aspect of your personality are you most grateful for?",
            "If you could have a conversation with your future self, what would you ask?",
            "What was the last decision you made that you’re truly proud of?",
            "How do you typically deal with procrastination?",
            "Recall a time you witnessed true generosity. What happened?",
            "Describe a moment when you felt genuinely free.",
            "What’s something that instantly relaxes you when you feel stressed?",
            "How do you react when your beliefs are challenged?",
            "If you had unlimited resources, how would you spend your time each day?",
            "Write about a time someone surprised you with kindness.",
            "What’s a small change you could make that would improve your daily routine?",
            "Recall a conversation that significantly changed your perspective.",
            "Name a person who inspires you to be better, and explain why.",
            "How do you handle moments of self-doubt?",
            "Describe a time you discovered a hidden talent—or realized you didn’t have one!",
            "Which personal value do you hold highest, and why?",
            "Write about a time when your curiosity led you somewhere interesting.",
            "What do you wish you had more time for?",
            "How do you balance personal needs with obligations to others?",
            "Describe a moment when you felt completely at peace with the world.",
            "Write about an item you own that has sentimental value.",
            "How does your physical environment (home, workspace) affect your mood?",
            "What’s a tradition (personal or cultural) that you love being a part of?",
            "If you could change one thing about your daily routine, what would it be?",
            "What does success look like in your personal relationships?",
            "How do you respond when someone asks you for help?",
            "Describe the last time you felt truly refreshed.",
            "Write about the impact of a decision you made years ago that still affects you today.",
            "What’s one question you would love to know the answer to?",
            "If you could learn a new language overnight, which would you choose and why?",
            "Describe a personal victory you experienced this year.",
            "How do you stay in touch with long-distance friends or family?",
            "Write about a moment that felt like a turning point in your life.",
            "What’s something you often take for granted but are thankful for?",
            "Who has been a consistent source of support in your life?",
            "Describe a time your patience was tested. How did you handle it?",
            "What do you think is your greatest strength?",
            "Write about a time you had to let go of something (or someone).",
            "Reflect on how your favorite season makes you feel.",
            "What’s your favorite part of the day, and why?",
            "Describe a time you felt genuinely excited about the future.",
            "If you could relive your childhood for a day, what would you do?",
            "Write about something that frustrates you and how you cope with it.",
            "Describe your ideal way to spend a long weekend.",
            "What’s your favorite way to celebrate milestones (big or small)?",
            "Write about a relationship in your life that has evolved over time.",
            "Which quality do you most appreciate in yourself right now?",
            "How do you handle it when you need to forgive someone?",
            "Describe the role of humor in your life. What makes you laugh the most?",
            "Write about a challenge you overcame that once seemed insurmountable.",
            "How do you practice self-compassion?",
            "Describe the moment you realized you were growing up.",
            "Write about a place you traveled to that left a lasting impression.",
            "How do you feel about endings—whether it’s a book, a show, or a chapter of life?",
            "Describe a time you helped a stranger (or they helped you).",
            "What’s a skill you believe everyone should learn?",
            "Reflect on a moment when you felt deeply grateful for your health.",
            "How do you react to unexpected changes in your plans?",
            "Write about a time someone’s faith in you made a big difference.",
            "What’s your idea of a perfect evening after a busy day?",
            "Name a stereotype about your generation or culture you’d like to debunk.",
            "What’s a personal flaw that you’re working on improving?",
            "Write about a time you felt your efforts went unrecognized. How did you handle it?",
            "How do you usually respond to constructive criticism?",
            "If you could live anywhere for a year, where would it be and why?",
            "Write about your morning ritual—or how you’d like it to be.",
            "Describe a project or idea you started but never finished. Do you still think about it?",
            "What’s the one thing in your life you’re the most consistent with?",
            "Write about the balance between your personal freedom and your responsibilities.",
            "Reflect on the last time you felt creatively inspired.",
            "What does the word 'forgiveness' mean to you?",
            "Describe a trait someone else has that you’d like to cultivate in yourself.",
            "Write about a regret you have and how you’ve learned from it.",
            "What’s the kindest thing you’ve done for yourself lately?",
            "Describe a small object in your room or home that has a big story behind it.",
            "How do you differentiate between wants and needs in your life?",
            "Write about a myth, legend, or story that fascinates you.",
            "What role does music play in your day-to-day life?",
            "Describe a time you felt lonely and what you did about it.",
            "What’s the biggest lesson you’ve learned from a mentor or teacher?",
            "Reflect on a time you chose to do the right thing even though it was hard.",
            "What book, TV show, or movie really shifted your worldview?",
            "Write about a topic you could talk about for hours without getting bored.",
            "How do you remind yourself to be present in the moment?",
            "Describe a significant loss you’ve experienced and how it changed you.",
            "Write about a time you stood up for someone who couldn’t stand up for themselves.",
            "How do you maintain meaningful connections with friends you don’t see often?",
            "Describe an experience where you felt completely out of your comfort zone.",
            "What’s one habit you’ve formed that you’re proud of?",
            "Write about a skill you admire in others but haven’t mastered yet.",
            "Reflect on a time you received support from an unexpected source.",
            "What’s something you wish more people understood about you?",
            "How do you handle worry or anxiety about things beyond your control?",
            "Write about an achievement you once thought was impossible.",
            "If you had the power to fix one global issue, which would you choose and why?",
            "Describe a time you felt an overwhelming sense of peace or calm.",
            "What’s the hardest lesson you’ve learned through friendship?",
            "Write about a moment you felt truly carefree.",
            "Reflect on something you find beautiful that others might overlook.",
            "How do you keep your perspective when times get tough?",
            "What is a personal boundary you’ve set, and why is it important to you?",
            "Describe an exciting idea or project you’d love to tackle someday.",
            "How do you approach conversations about sensitive or controversial topics?",
            "Write about a time you found unexpected joy in a routine activity.",
            "What does unconditional love mean to you?",
            "Recall a moment when you felt pure admiration for someone.",
            "What’s your favorite way to document your life—journaling, photos, videos, or something else?",
            "Describe a problem you solved recently and how it made you feel.",
            "How do you handle interruptions or distractions when you’re focused?",
            "Write about a time you got lost in something creative or artistic.",
            "What’s an important lesson you learned from your first job?",
            "Reflect on how you’ve changed since high school (or any significant past stage).",
            "Describe your approach to financial goals or budgeting.",
            "When was the last time you felt genuinely surprised by something?",
            "Write about a time you did something kind for yourself—self-care that really mattered.",
            "How do you navigate unexpected conflicts in your relationships?",
            "Describe a time you changed your mind about a deeply held belief.",
            "Write about the importance of laughter in your daily life.",
            "What’s one thing you could do each morning to improve your day?",
            "If you could learn about any historical event from a firsthand perspective, which would it be?",
            "Reflect on a time you felt completely safe and protected.",
            "Describe an experience that tested your patience and what you learned from it.",
            "What’s your biggest aspiration for the coming year?",
            "Write about the last time you felt nostalgic. What triggered it?",
            "How do you incorporate mindfulness or meditation into your life, if at all?",
            "Describe your favorite corner or space in your home and why it’s special.",
            "Think of someone you disagree with—how might you find common ground?",
            "Write about a time when your resilience was tested.",
            "What does relaxation look like to you when you’re overwhelmed?",
            "Describe a subject you’d love to teach or share with others.",
            "How do you respond when someone disappoints you?",
            "Write about your first memory of a pet or an animal encounter.",
            "What do you do when you feel the need to escape reality for a while?",
            "Describe a moment you felt proud of your own growth or maturity.",
            "What’s a personal mantra or motto you’ve created for yourself?",
            "Write about a childhood fear you’ve overcome.",
            "Describe an unexpected friendship or relationship that enriched your life.",
            "What do you do to remind yourself of your priorities?",
            "Write about a time you realized you needed to change your approach to something.",
            "What does empathy mean to you, and how do you practice it?",
            "How do you celebrate your cultural or family traditions, and why are they important?",
            "Write about a time you felt truly in tune with nature.",
            "Describe the impact of a single conversation that changed your direction.",
            "How do you cope when someone close to you is going through a difficult time?",
            "What was your biggest takeaway from this past month?",
            "Write about a memory that brings a sense of warmth whenever you revisit it.",
            "Describe a moment that made you feel deeply connected to someone else.",
            "How do you manage digital distractions in your life?",
            "Write about a trait you inherited from a family member.",
            "Who do you think of as a real-life hero, and why?",
            "What’s the most difficult apology you’ve ever had to make?",
            "Describe your sense of humor and how it’s evolved.",
            "Write about a situation where your perseverance paid off.",
            "What do you think you’ll be doing five years from now?",
            "How do you take care of your mental health on tough days?",
            "Reflect on a time you underestimated yourself—or someone else.",
            "Describe the best dessert you’ve ever had and the memory around it.",
            "What’s one piece of advice you’d give to someone younger than you?",
            "Write about a time you had to navigate cultural differences.",
            "How do you define 'living your best life' at this moment?",
            "Recall a time your intuition guided you correctly.",
            "What’s your favorite form of exercise or movement, and how does it make you feel?",
            "Write about a compliment you received that really stuck with you.",
            "Describe how you handle the fear of failure.",
            "What’s something you really want to learn but haven’t started yet?",
            "Write about an old hobby you’d like to revisit.",
            "How do you maintain connections with people from your past?",
            "Describe a time you faced rejection and how you moved forward.",
            "What are you looking forward to in the next season (literal or metaphorical)?",
            "Write about a practical skill you believe everyone should have.",
            "How do you stay authentic in a world filled with social pressure?",
            "Describe a recent moment that reminded you to appreciate life’s simple gifts.",
            "What is one trait you wish you had more of, and why?",
            "Write about a time you discovered a new passion or interest by accident.",
            "How do you balance ambition with contentment?",
            "Describe a part of your personality you don’t often show others.",
            "What’s something you wish people understood about your culture or background?",
            "Write about a day you felt especially productive—and what made it so.",
            "Reflect on a time you felt disconnected and how you found your way back.",
            "Describe a recurring dream or theme in your dreams and what you think it means.",
            "How do you usually make decisions—logic, gut feeling, or a mix of both?",
            "Write about a friendship that significantly shaped who you are.",
            "What’s one adventure (big or small) you’d love to embark on soon?",
            "How do you define the difference between being alone and feeling lonely?",
            "Describe a time you intentionally stepped out of your comfort zone.",
            "What’s your favorite way to celebrate a personal milestone?",
            "Reflect on a time when you were resilient in the face of unexpected hardship.",
            "What do you wish you spent less time worrying about?",
            "Describe a family tradition or recipe you’d like to pass on someday.",
            "Write about a moment you felt complete acceptance—from yourself or others.",
            "How do you approach learning from someone who disagrees with you?",
            "Write about a place in nature that makes you feel at peace.",
            "What’s one thing you used to hate but now love (or vice versa)?",
            "Describe your experience with journaling—how has it helped you?",
            "Write about a time someone showed unwavering loyalty to you.",
            "How do you differentiate between your own voice and others’ opinions in your head?",
            "What’s an unconventional thing that sparks joy for you?",
            "Describe a problem you’re currently trying to solve in your life.",
            "Write about the most unexpected compliment you’ve ever received.",
            "How do you handle failure when you’ve put in your best effort?",
            "Reflect on a subject you wish you’d studied more in school.",
            "What’s your approach to giving constructive feedback to others?",
            "Write about an experience that left you speechless, good or bad.",
            "Describe your ideal approach to handling conflict in relationships.",
            "What’s your favorite season or time of year, and why?",
            "Write about the last time you felt a strong sense of accomplishment.",
            "If you were to take a break from technology for a weekend, what would you do?",
            "Describe the best breakfast you’ve ever had and the memory surrounding it.",
            "Who do you trust for honest, constructive advice, and why?",
            "Reflect on a time when you helped a friend through a tough situation.",
            "What’s something you’re learning to accept about yourself?",
            "How do you respond when you see someone being treated unfairly?",
            "Write about your relationship with generosity—how do you give or receive?",
            "Describe a memory where you felt pure excitement for something new.",
            "What’s one belief you held strongly that changed significantly over time?",
            "How do you make the most of a day off?",
            "Write about a time you had to keep a secret. How did it weigh on you?",
            "Describe the qualities you think make a great leader.",
            "What’s one thing you wish you could tell people about your daily life?",
            "Reflect on your last travel experience—what did you learn from it?",
            "Write about a book that challenged your way of thinking.",
            "What do you do to re-center yourself when you feel overwhelmed?",
            "Describe your relationship with competition—do you thrive on it or avoid it?",
            "Reflect on a time you made a surprising connection with someone.",
            "What’s a piece of wisdom you’d share with a younger sibling or friend?",
            "How do you feel about asking for help when you need it?",
            "Write about the last time you tried a new food or cuisine.",
            "Describe a time you chose kindness over being 'right.'",
            "What’s your favorite way to document memories—photos, scrapbooking, etc.?",
            "How do you keep track of your goals and measure progress?",
            "Describe your stance on second chances—have you given or received them?",
            "Write about something you’re looking forward to doing this year.",
            "Reflect on a time you changed your opinion due to someone else’s perspective.",
            "What’s a movie scene or quote that always resonates with you?",
            "How do you incorporate mindfulness into daily tasks?",
            "Describe a time when teamwork made a hard task easier.",
            "What is something you often do for others that you find fulfilling?",
            "Reflect on a cultural custom you love (whether it’s your culture or not).",
            "What’s your favorite childhood vacation memory?",
            "Write about a challenge you overcame with sheer determination.",
            "Describe how you might want your future self to remember you now.",
            "What’s one characteristic you hope people associate with you?",
            "Reflect on how you celebrate progress, even if the goal isn’t reached yet.",
            "What does personal growth look like for you lately?",
            "Write about something you wish you could stop worrying about.",
            "How do you typically process sadness or grief?",
            "What’s your favorite creative medium (painting, cooking, writing, etc.) and why?",
            "Describe a time you had to learn something the 'hard way.'",
            "What is the best gift you’ve ever given someone else?",
            "Reflect on a time when you felt truly heard during a conversation.",
            "How do you handle sudden changes in your routine?",
            "Write about a stereotype you used to believe and how you moved past it.",
            "What do you think is the key to maintaining balance in life?",
            "Describe how your perspective on aging has evolved.",
            "How do you differentiate between what you want and what you actually need?",
            "Write about a routine you had as a child that you miss.",
            "Recall a time you felt like giving up but found a reason to keep going.",
            "How do you show love to people you care about?",
            "Describe a small victory you had this week that felt surprisingly good.",
            "What’s something you wish more people would talk openly about?",
            "Write about a skill or topic you feel you could mentor someone in.",
            "Reflect on the last time you felt a surge of confidence. What caused it?",
            "Describe how you handle unexpected praise or compliments.",
            "How do you like to celebrate your birthday (or do you not celebrate at all)?",
            "Write about a tradition you’d like to start for yourself or your family.",
            "What does your ideal 'healthy lifestyle' look like?",
            "Describe the first time you realized you were no longer a child.",
            "Reflect on something you used to be afraid of that no longer scares you.",
            "Write about the funniest thing that’s happened to you recently.",
            "Name a time you felt guilty about something. How did you deal with it?",
            "Describe a valuable lesson you’ve learned from a romantic relationship or close bond.",
            "Write about the last time you challenged yourself intellectually.",
            "Which subject do you find yourself reading about the most lately?",
            "How do you approach making amends when you’re in the wrong?",
            "What does friendship mean to you at this stage of your life?",
            "Recall a time someone offered you a fresh perspective. How did it help?",
            "Write about a hobby you’d like to take from casual interest to mastery.",
            "What’s the best compliment you’ve ever given or received?",
            "Describe a scenario where you had to take a leap of faith.",
            "Reflect on a piece of pop culture (song, show, etc.) that influenced you.",
            "How do you usually handle envy or jealousy?",
            "Write about a personality trait that others admire, but you struggle with.",
            "Describe a moment when you realized you were stronger than you thought.",
            "What do you do to remain hopeful during challenging times?",
            "Write about a piece of art (painting, sculpture, or performance) that moved you.",
            "If you could see a moment from your past with fresh eyes, which would it be?",
            "Describe a time when you felt truly immersed in the present moment.",
            "How do you set boundaries when it comes to technology or social media?",
            "Write about a cultural or family dish that’s meaningful to you.",
            "What’s one aspect of yourself you’d never want to change?",
            "Describe the last time you found joy in an unexpected place.",
            "Reflect on how your beliefs have evolved over the years.",
            "Write about a personal habit that you’ve been struggling to form (or break).",
            "What do you consider your greatest strength in relationships?",
            "How do you typically respond to unsolicited advice?",
            "Write about a time you realized your perspective was limited. What expanded it?",
            "Describe an element of nature (mountains, ocean, forest) that calls to you most.",
            "What’s your favorite way to spend time with someone you love?",
            "How do you keep track of milestones or achievements you’ve reached?",
            "Write about something in your life you consider a true blessing.",
            "Describe a time you had to rely on someone else. Was it easy or difficult?",
            "Reflect on a difficult conversation that ended better than you expected.",
            "What’s one way you can push your comfort zone in the near future?",
            "Write about a time you prioritized self-care over other demands.",
            "How do you respond to people who have different values from yours?",
            "Describe the last time you felt carefree and what contributed to it.",
            "What’s a character trait you inherited from a family member that you treasure?",
            "Write about a surprising lesson you learned from a mistake.",
            "Reflect on an unforgettable trip you took—what made it so memorable?",
            "How do you handle misunderstandings with close friends or family?",
            "Describe a positive change you’ve made in the last six months.",
            "Write about a topic you feel passionate enough to speak publicly on.",
            "What advice would you give to yourself five years ago?",
            "Reflect on a conversation that shifted your mindset about success or failure.",
            "What’s your go-to method for organizing your thoughts?",
            "Describe a memory that always brings a sense of warmth or nostalgia.",
            "How have you handled criticism from someone you respect?",
            "Write about a time you bonded with someone unexpectedly.",
            "Do you believe in fate, coincidence, or a mix of both? Why?",
            "Reflect on something you used to believe but have since questioned or abandoned.",
            "Describe a moment when you had to keep going even though you wanted to quit.",
            "What’s one indulgence or guilty pleasure you secretly love?",
            "Write about a phase in your life you look back on fondly.",
            "How do you typically handle decisions you end up regretting?",
            "Describe a family heirloom or story passed down through generations.",
            "Reflect on how you’ve grown in emotional maturity.",
            "What do you think is the most underrated emotion, and why?",
            "Write about a time your curiosity led to a new friendship or opportunity.",
            "How do you keep hope alive during tough or uncertain times?",
            "Describe your approach to budgeting or financial planning.",
            "What is a random act of kindness you did (or someone did for you)?",
            "Write about an experience that tested your adaptability.",
            "Reflect on a time you felt you were exactly where you needed to be.",
            "How do you manage your energy levels throughout the day?",
            "Describe a book character or fictional character you deeply relate to.",
            "What’s a comforting ritual you turn to when you’re feeling down?",
            "Write about a time you felt intimidated by something new but did it anyway.",
            "Reflect on the role that music plays in your self-expression.",
            "How do you define or measure success in your personal life?",
            "Write about the last time you explored a new city or neighborhood.",
            "Describe a conversation that made you question a long-held assumption.",
            "How do you remain patient with slow progress in any area of life?",
            "Reflect on the best piece of advice you ignored at first but later accepted.",
            "Write about a time you felt misunderstood or misjudged.",
            "Describe the morning routine that sets you up for a great day.",
            "What does being 'authentic' mean to you?",
            "Write about a relationship you healed after a falling out.",
            "How do you approach complex problems—logically, emotionally, or both?",
            "Reflect on a time you found out you were capable of more than you imagined.",
            "Describe a cause you’d volunteer for if you had unlimited time.",
            "What’s a hidden talent you suspect you might have but haven’t explored yet?",
            "Write about a time you had to say goodbye to someone or something.",
            "Reflect on how your cultural background shapes your daily life.",
            "What’s a dream you have for the world or society at large?",
            "Describe an experience that filled you with childlike wonder.",
            "Write about the best piece of advice someone gave you that you never forgot.",
            "How do you decide who to trust with your deepest secrets?",
            "Reflect on a time when silence spoke louder than words.",
            "What’s the most spontaneous thing you’ve ever done?",
            "Describe an older family member’s wisdom that you treasure.",
            "Write about a small, everyday miracle you’ve witnessed.",
            "How do you approach lifelong learning and personal development?",
            "Reflect on something that used to frustrate you but now amuses you.",
            "What do you do when your motivation levels are at an all-time low?",
            "Describe a time you stood alone on an issue you felt strongly about.",
            "Write about how you’ve navigated cultural or generational gaps in communication.",
            "How do you celebrate the little wins in your daily life?",
            "Reflect on a time when someone’s belief in you changed your trajectory.",
            "Describe the act of kindness you most recently experienced from a stranger.",
            "Write about a personal strength you never want to lose sight of.",
            "How do you stay disciplined when working toward a long-term goal?",
            "Reflect on a time you were overwhelmed by gratitude.",
            "What’s a childhood lesson that has stuck with you into adulthood?",
            "Describe a moment when you realized you had outgrown a fear or insecurity.",
            "Write about a habit you’re proud to have developed and maintained.",
            "How do you approach trying again after failing at something?",
            "Reflect on an aspect of your identity you’ve only recently embraced.",
            "Describe a defining moment in your career or education so far.",
            "Write about an unexpected ally you gained in a difficult situation.",
            "What role do personal affirmations play in your life, if any?",
            "Reflect on a memorable conversation you had with a close friend.",
            "How do you balance nostalgia for the past with living in the present?",
            "Write about a time you received forgiveness that you didn’t think you deserved.",
            "Describe the last time you felt very close to achieving a dream.",
            "Reflect on how you decide which relationships to invest your energy in.",
            "What’s a creative project you’d love to complete within the next year?",
            "Write about something that once felt impossible but now feels within reach.",
            "How do you manage conflicting emotions about a single situation?",
            "Describe the best vacation or getaway you’ve ever had.",
            "Write about a piece of clothing that holds special meaning for you.",
            "What lesson do you keep learning over and over in life?",
            "Reflect on how you like to mark the end of a chapter in your life.",
            "How do you react when someone blatantly disagrees with you?",
            "Write about a memorable interaction with a neighbor or community member.",
            "What’s a hobby you abandoned but might pick up again someday?",
            "Describe how you unwind after a very tense day or week.",
            "Reflect on an unexpected piece of advice that changed your mindset.",
            "Write about a place you consider your sanctuary or refuge.",
            "What’s something you wish you could tell everyone in the world?",
            "Describe a moment when you realized the importance of empathy.",
            "How do you typically handle plans that fall through at the last minute?",
            "Write about the most spontaneous decision you made that you don’t regret.",
            "Reflect on a memorable birthday or holiday and why it stood out.",
            "What’s a negative experience that led you toward a positive change?",
            "How do you discern when it’s time to move on from something or someone?",
            "Write about an invention you think would make life easier.",
            "Describe a way you’ve surprised yourself with your own creativity.",
            "What’s your go-to strategy when you’re feeling uninspired?",
            "Reflect on a moment where you felt unstoppable.",
            "Write about something you used to find embarrassing but have now embraced.",
            "How do you balance competing priorities in your life—like work, family, hobbies?",
            "Describe a time you gave someone the benefit of the doubt and it paid off.",
            "Reflect on a small interaction that restored your faith in humanity.",
            "Write about the first time you felt truly independent.",
            "How do you respond to someone who criticizes something you’re proud of?",
            "Reflect on a time you felt validated or acknowledged in a meaningful way.",
            "What’s a personal ritual you do, and how does it benefit you?",
            "Write about a moment where humor helped you cope with difficulty.",
            "Describe a summer memory that still makes you smile.",
            "Reflect on a family story you’ve been told repeatedly. What does it mean to you?",
            "What’s your approach to networking or meeting new people?",
            "Write about a time you faced a creative block and overcame it.",
            "How do you handle the weight of expectations—your own or others’?",
            "Reflect on something you like about your current life stage.",
            "Describe a night you couldn’t sleep. What kept you up?",
            "Write about an unanswered question that still fascinates you.",
            "What’s a trait you admire in someone close to you, and why?",
            "Reflect on a time you relied on sheer luck. Did it work out?",
            "Write about a criticism that actually helped you grow.",
            "How do you approach finding mentors or role models?",
            "Describe a movie or show scene that resonates with your personal experiences.",
            "Reflect on what you love most about your favorite hobby.",
            "Write about a place you’ve visited that felt like a second home.",
            "How do you cope with feeling overscheduled or too busy?",
            "Describe the best way someone has shown you they care.",
            "Write about a time you turned a challenging situation into an opportunity.",
            "What’s your personal philosophy on dealing with regret?",
            "Reflect on the times you’ve grown the most. What prompted that growth?",
            "Describe your relationship with money. How has it evolved?",
            "Write about an ‘aha!’ moment that changed your approach to life.",
            "How do you celebrate small milestones in a long-term project?",
            "Reflect on a compliment that caught you off guard but meant a lot.",
            "What’s one area of your life you’re trying to simplify?",
            "Write about a time you reconnected with an old friend and how it felt.",
            "How do you express gratitude toward yourself for your own efforts?",
            "Describe a moment when your perception of a person drastically changed.",
            "Reflect on an item you carry around with you often and why it’s significant.",
            "Write about your strategy for making new friends as an adult.",
            "How do you see your life philosophy shaping your future decisions?",
            "Describe a gift you gave someone that made you as happy as it made them.",
            "Reflect on the most productive day you’ve had recently—what factors helped?",
            "Write about how you see technology evolving in the next decade.",
            "What’s one habit from childhood you’re glad you outgrew?",
            "Describe a piece of artwork in your home that has a story behind it.",
            "Reflect on a moment you realized how important mental health is.",
            "Write about a teacher who challenged you to exceed your own expectations.",
            "What do you do when you need to reset your outlook on life?",
            "Describe a successful team effort you were part of. What made it work?",
            "Reflect on a time you had to reinvent yourself in some way.",
            "Write about the role compassion plays in your daily interactions.",
            "What’s a daily ritual you have that others might find quirky but you find essential?",
            "Describe a tough love moment you received and how it shaped you.",
            "Reflect on something that used to scare you about adulthood but doesn’t anymore.",
            "Write about a cause that you believe doesn’t get enough attention.",
            "What’s your unique way of staying organized, if any?",
            "Reflect on a book or resource that helped you develop a new perspective.",
            "Describe a moment when someone forgave you and how it affected you.",
            "Write about a stereotype related to your job, hobby, or lifestyle that you’d like to break.",
            "How do you handle it when you have to work (or collaborate) with someone you dislike?",
            "Reflect on your proudest moment of the past few months and why it mattered.",
            "What’s your strategy for finding balance between ambition and rest?",
            "Write about a hobby or pastime that keeps you grounded.",
            "Describe a time when letting go of control led to a better outcome.",
            "Reflect on how you practice patience in relationships or at work.",
            "What’s one small action you can do today that your future self will thank you for?",
            "Write about a misconception people often have about you.",
            "How do you maintain hope when facing obstacles that seem insurmountable?",
            "Describe something your community or neighborhood does well.",
            "Write about a sibling-like relationship in your life (whether biological or not).",
            "What’s a common thread you’ve noticed among your closest friends?",
            "Reflect on your very first memory. Why do you think it stuck with you?",
            "Write about your approach to prioritizing which tasks or projects get done first.",
            "How do you react to people who test your patience?",
            "Describe the qualities of an ideal mentor in your life.",
            "Write about the most important lesson you learned from a big mistake.",
            "What’s one way you can incorporate more joy into your routine?",
            "Reflect on a friendship that has lasted through major life changes.",
            "Write about a time you stood firm in your beliefs, even under pressure.",
            "What do you find most fulfilling about giving back to your community?",
            "How do you handle the pressure to compare your life to others’?",
            "Describe a technological advancement you’re grateful for and why.",
            "Write about your favorite childhood pastime and why it was special.",
            "What are you deeply curious about learning or exploring next?",
            "Reflect on a time when a risk led to an unexpected reward.",
            "Write about a challenge you’re facing at this moment and how you plan to tackle it.",
            "What was the highlight of your day today?",
            "Describe something you learned recently that fascinated you.",
            "Which small moment of kindness did you experience or witness today?",
            "What’s the biggest challenge on your mind right now?",
            "How do you feel about the weather today? Did it affect your mood?",
            "Describe a time you surprised yourself with your own strength or courage.",
            "What is one lesson you wish you could tell your younger self?",
            "Name three things that made you smile today.",
            "How do you like to recharge after a stressful day or week?",
            "If you had more free time, what new hobby would you like to explore?",
            "What personal goal are you currently working toward, and why?",
            "Reflect on a recent conversation that inspired you.",
            "What’s one thing you can do to take better care of your mind or body?",
            "How do you typically respond to conflict? Is there a better way?",
            "Write about a smell that takes you back in time.",
            "What do you value most in your closest relationships?",
            "Reflect on the best advice you’ve ever received.",
            "When do you feel most like your true self?",
            "What role does gratitude play in your life?",
            "How have you grown in the last year?",
            "What’s a common misconception people have about you?",
            "If you could instantly become an expert at something, what would it be and why?",
            "Reflect on a habit you’d like to break or build.",
            "What are you looking forward to in the next month?",
            "Describe your ideal morning routine.",
            "What does 'success' look like to you today?",
            "Recall a time you got lost (literally or metaphorically). What did you learn?",
            "Write about a book or movie that changed your perspective.",
            "Which qualities do you admire most in others?",
            "Describe a moment of pure joy you’ve experienced.",
            "How do you handle disappointment?",
            "What is your favorite day of the week and why?",
            "Name a time when you felt completely at peace.",
            "What is something new you’d like to try this year?",
            "Reflect on how technology influences your daily life.",
            "What is a recent mistake you made, and what did you learn from it?",
            "If you could have a conversation with anyone—past or present—who would it be?",
            "Write about a dream (sleeping dream or life dream) you vividly remember.",
            "What does self-care look like for you personally?",
            "Recall a time you had to deliver bad news. How did you handle it?",
            "What place in the world would you most like to visit and why?",
            "Describe your relationship with social media.",
            "What do you find most challenging about your current stage in life?",
            "If your day were a color, what color would it be and why?",
            "Reflect on an accomplishment you’re proud of.",
            "When did you last feel truly connected to nature?",
            "What is a topic or cause you’re passionate about, and why?",
            "Write about a time you took a big risk. How did it turn out?",
            "What’s your go-to strategy for dealing with anxiety or stress?",
            "Describe an act of kindness you performed or witnessed recently.",
            "Is there a childhood memory that still makes you laugh? Describe it.",
            "What’s your favorite way to express creativity?",
            "Write about the last time you felt really proud of someone else.",
            "Reflect on a fear or phobia you have. Where do you think it originates?",
            "How does your environment influence your mood or productivity?",
            "What’s your earliest memory of feeling truly happy?",
            "If money were no object, how would you spend your days?",
            "What’s one thing you’d like people to remember you for?",
            "Describe a time you felt misunderstood. How did you handle it?",
            "Which aspect of your personality do you value the most?",
            "Write about a time you had to ask for help. How did it feel?",
            "Do you find it easy or difficult to forgive? Why?",
            "Reflect on a time when you changed your mind about something important.",
            "What is your definition of friendship?",
            "Talk about a favorite tradition or holiday memory.",
            "Write about a recent decision you made that you feel really good about.",
            "How do you handle boredom?",
            "What’s something you know now that you wish you knew five years ago?",
            "Write about a time you felt deeply appreciated by someone.",
            "What are three positive adjectives you would use to describe yourself?",
            "Reflect on a challenge you overcame that once seemed impossible.",
            "Who was the most interesting person you interacted with today?",
            "What was the best part of your day?",
            "How did you see the hand of the Lord (or a higher power) in your life today?",
            "What was the strongest emotion you felt today?",
            "If you had one thing you could do over today, what would it be?",
            "Write about an everyday moment that was unexpectedly meaningful.",
            "Is there something that always brings you comfort? Describe it.",
            "What’s the last thing that made you laugh out loud?",
            "Reflect on your favorite place to relax and unwind.",
            "Write about a time you successfully resolved a conflict.",
            "What does hope mean to you personally?",
            "Describe a time you had to be brave.",
            "If you could have any superpower, what would it be and why?",
            "What small act of kindness can you do tomorrow?",
            "Reflect on a quality in yourself you used to see as a weakness but now see as a strength.",
            "What’s your relationship with physical exercise or movement?",
            "If you were writing a book about your life, what would today’s chapter be called?",
            "Write about something you're really looking forward to this week or month.",
            "Describe a meal that had special meaning for you.",
            "What moment from today do you want to remember weeks from now?",
            "What does your dream home look and feel like?",
            "Reflect on a time you helped someone in need.",
            "Do you have a personal motto or mantra? If so, what is it?",
            "What's one lesson you’ve learned from failure?",
            "Write about a moment of spontaneous joy you experienced.",
            "Name three simple pleasures you’re grateful for right now.",
            "Describe a time when you felt a strong sense of connection to others.",
            "What kind of legacy do you want to leave behind?",
            "Reflect on your favorite season. What do you love about it?",
            "If you could relive any day of your life, which would it be and why?",
            "Write about how you manage or think about time.",
            "Describe a skill you’d like to pass on to others, and why it’s important to you."

         };

    public string GetRandomPrompt()
    {
        int index = _random.Next(_prompts.Count);
        return _prompts[index];
    }

}